export const FLUSH_REVIEWS = 'FLUSH_REVIEWS';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_LOADING = 'GET_REVIEWS_LOADING';
export const GET_REVIEWS_ERROR = 'GET_REVIEWS_ERROR';

export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_LOADING = 'ADD_REVIEW_LOADING';
export const ADD_REVIEW_ERROR = 'ADD_REVIEW_ERROR';
